- name: create oai config directory
  file:
    path: /usr/local/etc/oai/freeDiameter
    state: directory

- name: overwrite oai epc configs
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: 'acl.j2', dest: '/usr/local/etc/oai/freeDiameter/acl.conf' }
#    - { src: 'spgw.j2', dest: '/usr/local/etc/oai/spgw.conf' }
